### ISSUE TITLE
Feedback to your IPERKA document

### ISSUE THREAD

**Issue by tbz-neil-devlin** [Timofey-Makhankov/Tic-Tac-Toe-Website#10]
Information
"After a quick research we knew how to do it." - You need to provide how you did the research, provide URL's etc

Decision
- The decision matrix needs to be re-worked as discussed in class
- The decisions who does what should be in bullet-points

Planning
- The Gant diagram is good
  - Requirements planning - where is the list of requirements?
  - Write specification - where is the specification doc?
  - Write test plan - where are the testplan & testcases?
- What I am missing is a list of who does which task and how long does the task(s) take (resource plan). This is to see that the workload is evenly distributed

Realisation
- "We make a sketch drawing": - include the sketch in your document
- "If the Outcome wasn't desired, we would try to resolve it" - provide examples

**Comment by Timofey-Makhankov** [comment]
The Feedback has been taken and improved
