### ISSUE TITLE
Add project plan to your IPERKA document

### ISSUE THREAD

**Issue by tbz-neil-devlin** [Timofey-Makhankov/Tic-Tac-Toe-Website#2]
You need to add your plan (as a screenshot)
Make sure that the plan shows all the work up to 

As there are 3 of you I would also like to see a resource plan (planned absences)
Tasks lists should be tracked in Excel (or similar) or even as issues (like I am doing now)

**Comment by Timofey-Makhankov** [comment]
Do we need to out it as a seperate document inside a folder on the Repo or in the README File?

**Comment by Timofey-Makhankov** [comment]
This has been added to the README File
